export const serviceData = [
    { type: "Oil Change", cost: 50 },
    { type: "Tire Rotation", cost: 30 },
    { type: "Brake Replacement", cost: 150 },
    { type: "Battery Replacement", cost: 100 },
    { type: "Air Conditioning Service", cost: 80 },
    { type: "Transmission Fluid Flush", cost: 120 },
    { type: "Engine Tune-up", cost: 100 },
    { type: "Wheel Alignment", cost: 60 },
    { type: "Spark Plug Replacement", cost: 50 },
    { type: "Fuel System Cleaning", cost: 90 }
  ];
  

export const cities = [
  "New York City, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Columbus, OH",
  "Fort Worth, TX",
  "Charlotte, NC",
  "Detroit, MI",
  "El Paso, TX",
  "Seattle, WA",
];

export const carData = [
  { make: "Toyota", model: "Camry" },
  { make: "Toyota", model: "Corolla" },
  { make: "Toyota", model: "RAV4" },
  { make: "Toyota", model: "Prius" },
  { make: "Toyota", model: "Highlander" },
  { make: "Toyota", model: "Sienna" },
  { make: "Toyota", model: "Tacoma" },
  { make: "Toyota", model: "Tundra" },
  { make: "Toyota", model: "4Runner" },
  { make: "Honda", model: "Accord" },
  { make: "Honda", model: "Civic" },
  { make: "Honda", model: "CR-V" },
  { make: "Honda", model: "Pilot" },
  { make: "Honda", model: "Odyssey" },
  { make: "Honda", model: "Ridgeline" },
  { make: "Honda", model: "Civic Type R" },
  { make: "Honda", model: "HR-V" },
  { make: "Honda", model: "Fit" },
  { make: "Honda", model: "Insight" },
  { make: "Audi", model: "A4" },
  { make: "Audi", model: "A6" },
  { make: "Audi", model: "Q3" },
  { make: "Audi", model: "Q5" },
  { make: "Audi", model: "Q7" },
  { make: "Audi", model: "Q8" },
  { make: "Audi", model: "RS3" },
  { make: "Audi", model: "RS5" },
  { make: "Audi", model: "S4" },
  { make: "Audi", model: "S5" },
  { make: "BMW", model: "3 Series" },
  { make: "BMW", model: "5 Series" },
  { make: "BMW", model: "7 Series" },
  { make: "BMW", model: "X3" },
  { make: "BMW", model: "X5" },
  { make: "BMW", model: "X7" },
  { make: "BMW", model: "M3" },
  { make: "BMW", model: "M5" },
  { make: "BMW", model: "i3" },
  { make: "BMW", model: "i8" },
  { make: "Ford", model: "Mustang" },
  { make: "Ford", model: "F-150" },
  { make: "Ford", model: "Focus" },
  { make: "Ford", model: "Explorer" },
  { make: "Ford", model: "Escape" },
  { make: "Ford", model: "Edge" },
  { make: "Ford", model: "Ranger" },
  { make: "Ford", model: "Fusion" },
  { make: "Ford", model: "Expedition" },
  { make: "Ford", model: "Bronco" },
  { make: "Nissan", model: "Altima" },
  { make: "Nissan", model: "Sentra" },
  { make: "Nissan", model: "Rogue" },
  { make: "Nissan", model: "Versa" },
  { make: "Nissan", model: "Maxima" },
  { make: "Nissan", model: "Pathfinder" },
  { make: "Nissan", model: "Murano" },
  { make: "Nissan", model: "Titan" },
  { make: "Nissan", model: "Frontier" },
  { make: "Nissan", model: "Leaf" },
  { make: "Hyundai", model: "Elantra" },
  { make: "Hyundai", model: "Sonata" },
  { make: "Hyundai", model: "Tucson" },
  { make: "Hyundai", model: "Santa Fe" },
  { make: "Hyundai", model: "Kona" },
  { make: "Hyundai", model: "Veloster" },
  { make: "Hyundai", model: "Accent" },
  { make: "Hyundai", model: "Genesis" },
  { make: "Hyundai", model: "Ioniq" },
  { make: "Hyundai", model: "Palisade" }
];

export const years = [
    2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
    2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
    2021, 2022, 2023
  ];

export const carServiceStages = [
  "Check-In",
  "Inspection",
  "Diagnosis",
  "Estimation",
  "Approval",
  "Repair",
  "Quality Check",
  "Final Inspection",
  "Payment",
  "Completed"
];



  
